// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTniCeV2jRhzsGsLJnJvlVTThBY5Ivbo0',
    appId: '1:185142124284:android:80fdc59c1e1edb28d68179',
    messagingSenderId: '185142124284',
    projectId: 'anees-a0de5',
    databaseURL: 'https://anees-a0de5-default-rtdb.firebaseio.com',
    storageBucket: 'anees-a0de5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6c6D7-3KRqKuKT19S8_4Hvn6CleuUVjw',
    appId: '1:185142124284:ios:638f3d45187c7390d68179',
    messagingSenderId: '185142124284',
    projectId: 'anees-a0de5',
    databaseURL: 'https://anees-a0de5-default-rtdb.firebaseio.com',
    storageBucket: 'anees-a0de5.appspot.com',
    androidClientId: '185142124284-ivve6pkne45mjl84n2vn1805tjpdbdcn.apps.googleusercontent.com',
    iosClientId: '185142124284-47nguffvfvkih0ag4v72ndu1bnsodpol.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication27',
  );
}
